### ISSUE TITLE
Issue while connecting to networks with `SSID` having more than 1 string

### ISSUE THREAD

**Issue by TanmayPatil105** [TanmayPatil105/wifi-cli#16]

**Comment by hrithiksawhney** [comment]
Can I work on this?

**Comment by youpong** [comment]
Would you mind describing how to reproduce?

**Comment by hrithiksawhney** [comment]
Yes, please rename your wifi SSID with a string having multiple spaces. And try to run the command `wifi connect "$SSID"`.

**Comment by TanmayPatil105** [comment]
Fixed in #18
