### ISSUE TITLE
Add `nmcli` as dependency

### ISSUE THREAD

**Issue by TanmayPatil105** [TanmayPatil105/wifi-cli#2]
The shell script uses `nmcli` command which can be listed on dependencies.

**Comment by hrithiksawhney** [comment]
Can I work on this?

**Comment by hrithiksawhney** [comment]
Hi @TanmayPatil105 ,
Do you want to add this command as part of install.sh file or just a mention in the Readme.md file?

**Comment by TanmayPatil105** [comment]
As a part of install.sh!
