### ISSUE TITLE
Do not connect wifi to an already connected network-ssid

### ISSUE THREAD

**Issue by hrithiksawhney** [TanmayPatil105/wifi-cli#21]
We should not connect wifi to an already connected network SSID as this will add multiple instances of the same network SSID in the `/etc/NetworkManager/system-connections` as shown in the below screenshot due to which a user will not be able to use the forget command (`wifi forget $SSID`) to forget the network.

![Screenshot from 2022-10-23 02-57-07](https://user-images.githubusercontent.com/44416769/197363219-00b4f1dd-7195-4c19-b128-196ec2c5afc2.png)

**Comment by hrithiksawhney** [comment]
Can you please assign this to me?

**Comment by TanmayPatil105** [comment]
Even I have aliased files but the only difference is that there is only a `single` alias file even after trying to connect to Network multiple times.

**Comment by hrithiksawhney** [comment]
@TanmayPatil105, even if only a single alias file is created, it leads to the issue that when the user tries to forget the network using the original SSID and then tries to connect to the same network SSID again, an alias file is created instead of a file with the original SSID. 

For example, consider the following content in `/etc/NetworkManager/system-connections`  where `example` is the name of the SSID:
example
example 1

After forgetting the original network SSID, the content will be:
example 1

After trying to connect to the same network SSID, the content will be:
example 1
example 2

**Comment by TanmayPatil105** [comment]
Ohh I see!

**Comment by TanmayPatil105** [comment]
check if the alias files have the same password  `psk` stored as the original file!
In my case, No password is stored in `alias` file!

**Comment by hrithiksawhney** [comment]
In my case, yes, same password `psk` as the original file is stored in the alias files.

**Comment by TanmayPatil105** [comment]
Fixed in #25
