### ISSUE TITLE
Install sudo to the docker image

### ISSUE THREAD

**Issue by youpong** [TanmayPatil105/wifi-cli#27]
## Description

Install sudo to the docker image so that use the same `install.sh` instead of `docker-install.sh`.

See [procfetch's Dockerfile](https://github.com/TanmayPatil105/procfetch/blob/main/Dockerfile). This one installs sudo.

**Comment by TanmayPatil105** [comment]
Are you working on it?

**Comment by youpong** [comment]
No.

**Comment by TanmayPatil105** [comment]
@youpong checkout new branch `docker`.
Mention changes if any!!

**Comment by youpong** [comment]
Excellent work!

To make it better:
- move line 2 to line 9.
- uncomment line 4.

**Comment by TanmayPatil105** [comment]
Sure! Thanks :)

**Comment by youpong** [comment]
done by #28.
