### ISSUE TITLE
Always ends with error

### ISSUE THREAD

**Issue by youpong** [TanmayPatil105/wifi-cli#3]
## Describe the bug

If the program is completed successfully, it's exit code should be 0 as the UNIX convention.
However `wifi` always returns exit code 1.

## To Reproduce

1. Type the command `wifi -h`
1. Type the command `echo $?`

```
1
```

## expected

```
0
```

**Comment by TanmayPatil105** [comment]
Fixed `abnormal termination of program` with exit code 1 in the recent push.
