### ISSUE TITLE
Add color to the connected network in wifi list

### ISSUE THREAD

**Issue by TanmayPatil105** [TanmayPatil105/wifi-cli#5]
After executing `wifi list`, if we are connected to a network then it should be highlighted with green color.

**Comment by TanmayPatil105** [comment]
currently only a ` * ` is getting printed before the connected Network

**Comment by Kabiirk** [comment]
Hi,
Can I work on this ? 
I think this can be implemented using ANSI characters

**Comment by TanmayPatil105** [comment]
If you need any help doing this. You can dm me on discord!!

**Comment by Kabiirk** [comment]
Sure thing ! Will get in touch in case I have any queries !

**Comment by TanmayPatil105** [comment]
Solved in the recent [commit](https://github.com/TanmayPatil105/wifi-cli/commit/163f5648c46acf7ae244a757dcc0ee6186bb166d) !
