### ISSUE TITLE
format help.txt

### ISSUE THREAD

**Issue by TanmayPatil105** [TanmayPatil105/wifi-cli#6]
The contents of `wifi --help` or `wifi -h`  can be displayed in a well formated form.

**Comment by TanmayPatil105** [comment]
The way man pages look!

**Comment by plopez26DPU** [comment]
Ok, assign me the issue please

**Comment by TanmayPatil105** [comment]
Closed in the recent commit [commit](https://github.com/TanmayPatil105/wifi-cli/commit/6556c800b6446101e615e598a3b18d5597122a21).
